name: Sync station database

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * 0'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Remove stale DB file
        run: rm -f stations.db
      - name: Get inventory data
        run: mysql2sqlite -f stations.db -d ${{ secrets.INVENTORY_DB }} -u ${{ secrets.INVENTORY_USER }} --mysql-password ${{ secrets.INVENTORY_PASSWORD }} -h ${{ secrets.INVENTORY_HOST }}
      - name: Get station data
        run: python database.py
      - name: Upload stations database file via FTP
        run: |
          curl -T ./stations.db \
            --user "${{ secrets.FTP_USER }}:${{ secrets.FTP_PASSWORD }}" \
            "ftp://${{ secrets.FTP_HOST }}/stations.db"
      - name: Commit Files
        run: |
          git config --local user.email "${{ vars.GIT_EMAIL }}"
          git config --local user.name "${{ vars.GIT_USER }}"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Sync stations" --allow-empty)
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}